defmodule Cortex.Messaging.Message do
  @moduledoc """
  Immutable message struct for inter-agent communication.

  Every message exchanged between agents flows through this struct. It
  carries sender/receiver identifiers, typed content, and metadata for
  observability.

  ## Fields

    - `id` — UUID v4, auto-generated by `new/1`
    - `from` — agent_id or team name (string) of the sender
    - `to` — agent_id, team name (string), or `:broadcast` (atom)
    - `content` — any term (string, map, list, etc.)
    - `type` — one of `:message`, `:request`, `:response`, `:result`, `:error`
    - `timestamp` — UTC `DateTime`, auto-generated by `new/1`
    - `metadata` — optional map for extra routing/tracing data

  ## Examples

      iex> msg = Cortex.Messaging.Message.new(%{from: "agent-1", to: "agent-2", content: "hello"})
      iex> msg.type
      :message

  """

  @valid_types [:message, :request, :response, :result, :error]

  @enforce_keys [:id, :from, :to, :content]
  defstruct [:id, :from, :to, :content, :type, :timestamp, :metadata]

  @type message_type :: :message | :request | :response | :result | :error

  @type t :: %__MODULE__{
          id: String.t(),
          from: String.t(),
          to: String.t() | :broadcast,
          content: term(),
          type: message_type(),
          timestamp: DateTime.t(),
          metadata: map() | nil
        }

  @doc """
  Creates a new `Message` with auto-generated UUID and timestamp.

  ## Parameters

    - `attrs` — a map with at least `:from`, `:to`, and `:content`.
      Optional keys: `:type` (defaults to `:message`), `:metadata`.

  ## Returns

    - `%Message{}` with `:id` and `:timestamp` filled in

  ## Examples

      iex> msg = Message.new(%{from: "a", to: "b", content: "hi"})
      iex> is_binary(msg.id) and msg.type == :message
      true

  """
  @spec new(map()) :: t()
  def new(%{from: from, to: to, content: content} = attrs) do
    type = Map.get(attrs, :type, :message)

    unless type in @valid_types do
      raise ArgumentError,
            "invalid message type: #{inspect(type)}, must be one of #{inspect(@valid_types)}"
    end

    %__MODULE__{
      id: Uniq.UUID.uuid4(),
      from: from,
      to: to,
      content: content,
      type: type,
      timestamp: DateTime.utc_now(),
      metadata: Map.get(attrs, :metadata)
    }
  end

  @doc """
  Returns the list of valid message type atoms.
  """
  @spec valid_types() :: [message_type()]
  def valid_types, do: @valid_types
end
