// Cortex Agent Gateway — gRPC service contract.
//
// This proto defines the bidirectional streaming RPC between the Go sidecar
// and the Elixir gateway. Both sides generate typed stubs from this single
// source of truth.
//
// Package: cortex.gateway.v1
// Go package: gatewayv1

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: cortex/gateway/v1/gateway.proto

package gatewayv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentGateway_Connect_FullMethodName = "/cortex.gateway.v1.AgentGateway/Connect"
)

// AgentGatewayClient is the client API for AgentGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentGateway is the data-plane service for agent mesh connectivity.
// Agents connect via a long-lived bidirectional stream. The first message
// from the agent MUST be a RegisterRequest.
type AgentGatewayClient interface {
	// Connect opens a bidirectional stream between a sidecar and the gateway.
	// The first AgentMessage MUST be a RegisterRequest.
	// The gateway responds with RegisterResponse, then both sides exchange
	// messages asynchronously for the lifetime of the connection.
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, GatewayMessage], error)
}

type agentGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentGatewayClient(cc grpc.ClientConnInterface) AgentGatewayClient {
	return &agentGatewayClient{cc}
}

func (c *agentGatewayClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, GatewayMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentGateway_ServiceDesc.Streams[0], AgentGateway_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentMessage, GatewayMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentGateway_ConnectClient = grpc.BidiStreamingClient[AgentMessage, GatewayMessage]

// AgentGatewayServer is the server API for AgentGateway service.
// All implementations must embed UnimplementedAgentGatewayServer
// for forward compatibility.
//
// AgentGateway is the data-plane service for agent mesh connectivity.
// Agents connect via a long-lived bidirectional stream. The first message
// from the agent MUST be a RegisterRequest.
type AgentGatewayServer interface {
	// Connect opens a bidirectional stream between a sidecar and the gateway.
	// The first AgentMessage MUST be a RegisterRequest.
	// The gateway responds with RegisterResponse, then both sides exchange
	// messages asynchronously for the lifetime of the connection.
	Connect(grpc.BidiStreamingServer[AgentMessage, GatewayMessage]) error
	mustEmbedUnimplementedAgentGatewayServer()
}

// UnimplementedAgentGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentGatewayServer struct{}

func (UnimplementedAgentGatewayServer) Connect(grpc.BidiStreamingServer[AgentMessage, GatewayMessage]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedAgentGatewayServer) mustEmbedUnimplementedAgentGatewayServer() {}
func (UnimplementedAgentGatewayServer) testEmbeddedByValue()                      {}

// UnsafeAgentGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentGatewayServer will
// result in compilation errors.
type UnsafeAgentGatewayServer interface {
	mustEmbedUnimplementedAgentGatewayServer()
}

func RegisterAgentGatewayServer(s grpc.ServiceRegistrar, srv AgentGatewayServer) {
	// If the following call panics, it indicates UnimplementedAgentGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentGateway_ServiceDesc, srv)
}

func _AgentGateway_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentGatewayServer).Connect(&grpc.GenericServerStream[AgentMessage, GatewayMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentGateway_ConnectServer = grpc.BidiStreamingServer[AgentMessage, GatewayMessage]

// AgentGateway_ServiceDesc is the grpc.ServiceDesc for AgentGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cortex.gateway.v1.AgentGateway",
	HandlerType: (*AgentGatewayServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _AgentGateway_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "cortex/gateway/v1/gateway.proto",
}
