// Cortex Agent Gateway — gRPC service contract.
//
// This proto defines the bidirectional streaming RPC between the Go sidecar
// and the Elixir gateway. Both sides generate typed stubs from this single
// source of truth.
//
// Package: cortex.gateway.v1
// Go package: gatewayv1

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: cortex/gateway/v1/gateway.proto

package gatewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AgentStatus represents the operational state of an agent.
type AgentStatus int32

const (
	// Default zero value — must not be used as a real status.
	AgentStatus_AGENT_STATUS_UNSPECIFIED AgentStatus = 0
	// Agent is idle and available for work.
	AgentStatus_AGENT_STATUS_IDLE AgentStatus = 1
	// Agent is actively working on a task.
	AgentStatus_AGENT_STATUS_WORKING AgentStatus = 2
	// Agent is draining — finishing current work, not accepting new tasks.
	AgentStatus_AGENT_STATUS_DRAINING AgentStatus = 3
	// Agent has disconnected from the gateway.
	AgentStatus_AGENT_STATUS_DISCONNECTED AgentStatus = 4
)

// Enum value maps for AgentStatus.
var (
	AgentStatus_name = map[int32]string{
		0: "AGENT_STATUS_UNSPECIFIED",
		1: "AGENT_STATUS_IDLE",
		2: "AGENT_STATUS_WORKING",
		3: "AGENT_STATUS_DRAINING",
		4: "AGENT_STATUS_DISCONNECTED",
	}
	AgentStatus_value = map[string]int32{
		"AGENT_STATUS_UNSPECIFIED":  0,
		"AGENT_STATUS_IDLE":         1,
		"AGENT_STATUS_WORKING":      2,
		"AGENT_STATUS_DRAINING":     3,
		"AGENT_STATUS_DISCONNECTED": 4,
	}
)

func (x AgentStatus) Enum() *AgentStatus {
	p := new(AgentStatus)
	*p = x
	return p
}

func (x AgentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_cortex_gateway_v1_gateway_proto_enumTypes[0].Descriptor()
}

func (AgentStatus) Type() protoreflect.EnumType {
	return &file_cortex_gateway_v1_gateway_proto_enumTypes[0]
}

func (x AgentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentStatus.Descriptor instead.
func (AgentStatus) EnumDescriptor() ([]byte, []int) {
	return file_cortex_gateway_v1_gateway_proto_rawDescGZIP(), []int{0}
}

// TaskStatus represents the outcome of a completed task.
type TaskStatus int32

const (
	// Default zero value — must not be used as a real status.
	TaskStatus_TASK_STATUS_UNSPECIFIED TaskStatus = 0
	// Task completed successfully.
	TaskStatus_TASK_STATUS_COMPLETED TaskStatus = 1
	// Task failed.
	TaskStatus_TASK_STATUS_FAILED TaskStatus = 2
	// Task was cancelled.
	TaskStatus_TASK_STATUS_CANCELLED TaskStatus = 3
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "TASK_STATUS_COMPLETED",
		2: "TASK_STATUS_FAILED",
		3: "TASK_STATUS_CANCELLED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED": 0,
		"TASK_STATUS_COMPLETED":   1,
		"TASK_STATUS_FAILED":      2,
		"TASK_STATUS_CANCELLED":   3,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_cortex_gateway_v1_gateway_proto_enumTypes[1].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_cortex_gateway_v1_gateway_proto_enumTypes[1]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_cortex_gateway_v1_gateway_proto_rawDescGZIP(), []int{1}
}

// AgentMessage is the envelope for all agent-to-gateway messages.
// Exactly one of the oneof fields must be set.
type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*AgentMessage_Register
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_TaskResult
	//	*AgentMessage_StatusUpdate
	//	*AgentMessage_PeerResponse
	//	*AgentMessage_DirectMessage
	//	*AgentMessage_Broadcast
	Msg           isAgentMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_cortex_gateway_v1_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_gateway_v1_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_cortex_gateway_v1_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetMsg() isAgentMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *AgentMessage) GetRegister() *RegisterRequest {
	if x != nil {
		if x, ok := x.Msg.(*AgentMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Msg.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetTaskResult() *TaskResult {
	if x != nil {
		if x, ok := x.Msg.(*AgentMessage_TaskResult); ok {
			return x.TaskResult
		}
	}
	return nil
}

func (x *AgentMessage) GetStatusUpdate() *StatusUpdate {
	if x != nil {
		if x, ok := x.Msg.(*AgentMessage_StatusUpdate); ok {
			return x.StatusUpdate
		}
	}
	return nil
}

func (x *AgentMessage) GetPeerResponse() *PeerResponse {
	if x != nil {
		if x, ok := x.Msg.(*AgentMessage_PeerResponse); ok {
			return x.PeerResponse
		}
	}
	return nil
}

func (x *AgentMessage) GetDirectMessage() *DirectMessage {
	if x != nil {
		if x, ok := x.Msg.(*AgentMessage_DirectMessage); ok {
			return x.DirectMessage
		}
	}
	return nil
}

func (x *AgentMessage) GetBroadcast() *BroadcastRequest {
	if x != nil {
		if x, ok := x.Msg.(*AgentMessage_Broadcast); ok {
			return x.Broadcast
		}
	}
	return nil
}

type isAgentMessage_Msg interface {
	isAgentMessage_Msg()
}

type AgentMessage_Register struct {
	// Registration request — must be the first message on the stream.
	Register *RegisterRequest `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type AgentMessage_Heartbeat struct {
	// Periodic heartbeat to keep the agent alive in the registry.
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_TaskResult struct {
	// Result of a completed/failed task.
	TaskResult *TaskResult `protobuf:"bytes,3,opt,name=task_result,json=taskResult,proto3,oneof"`
}

type AgentMessage_StatusUpdate struct {
	// Progress update from the agent.
	StatusUpdate *StatusUpdate `protobuf:"bytes,4,opt,name=status_update,json=statusUpdate,proto3,oneof"`
}

type AgentMessage_PeerResponse struct {
	// Response to a peer invocation.
	PeerResponse *PeerResponse `protobuf:"bytes,5,opt,name=peer_response,json=peerResponse,proto3,oneof"`
}

type AgentMessage_DirectMessage struct {
	// Direct message to a specific agent (gateway routes by to_agent).
	DirectMessage *DirectMessage `protobuf:"bytes,6,opt,name=direct_message,json=directMessage,proto3,oneof"`
}

type AgentMessage_Broadcast struct {
	// Broadcast message to all agents.
	Broadcast *BroadcastRequest `protobuf:"bytes,7,opt,name=broadcast,proto3,oneof"`
}

func (*AgentMessage_Register) isAgentMessage_Msg() {}

func (*AgentMessage_Heartbeat) isAgentMessage_Msg() {}

func (*AgentMessage_TaskResult) isAgentMessage_Msg() {}

func (*AgentMessage_StatusUpdate) isAgentMessage_Msg() {}

func (*AgentMessage_PeerResponse) isAgentMessage_Msg() {}

func (*AgentMessage_DirectMessage) isAgentMessage_Msg() {}

func (*AgentMessage_Broadcast) isAgentMessage_Msg() {}

// GatewayMessage is the envelope for all gateway-to-agent messages.
// Exactly one of the oneof fields must be set.
type GatewayMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*GatewayMessage_Registered
	//	*GatewayMessage_TaskRequest
	//	*GatewayMessage_PeerRequest
	//	*GatewayMessage_RosterUpdate
	//	*GatewayMessage_Error
	//	*GatewayMessage_DirectMessage
	Msg           isGatewayMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayMessage) Reset() {
	*x = GatewayMessage{}
	mi := &file_cortex_gateway_v1_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayMessage) ProtoMessage() {}

func (x *GatewayMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_gateway_v1_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayMessage.ProtoReflect.Descriptor instead.
func (*GatewayMessage) Descriptor() ([]byte, []int) {
	return file_cortex_gateway_v1_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *GatewayMessage) GetMsg() isGatewayMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *GatewayMessage) GetRegistered() *RegisterResponse {
	if x != nil {
		if x, ok := x.Msg.(*GatewayMessage_Registered); ok {
			return x.Registered
		}
	}
	return nil
}

func (x *GatewayMessage) GetTaskRequest() *TaskRequest {
	if x != nil {
		if x, ok := x.Msg.(*GatewayMessage_TaskRequest); ok {
			return x.TaskRequest
		}
	}
	return nil
}

func (x *GatewayMessage) GetPeerRequest() *PeerRequest {
	if x != nil {
		if x, ok := x.Msg.(*GatewayMessage_PeerRequest); ok {
			return x.PeerRequest
		}
	}
	return nil
}

func (x *GatewayMessage) GetRosterUpdate() *RosterUpdate {
	if x != nil {
		if x, ok := x.Msg.(*GatewayMessage_RosterUpdate); ok {
			return x.RosterUpdate
		}
	}
	return nil
}

func (x *GatewayMessage) GetError() *Error {
	if x != nil {
		if x, ok := x.Msg.(*GatewayMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *GatewayMessage) GetDirectMessage() *DirectMessage {
	if x != nil {
		if x, ok := x.Msg.(*GatewayMessage_DirectMessage); ok {
			return x.DirectMessage
		}
	}
	return nil
}

type isGatewayMessage_Msg interface {
	isGatewayMessage_Msg()
}

type GatewayMessage_Registered struct {
	// Registration confirmation with assigned agent ID.
	Registered *RegisterResponse `protobuf:"bytes,1,opt,name=registered,proto3,oneof"`
}

type GatewayMessage_TaskRequest struct {
	// Task assignment from Cortex.
	TaskRequest *TaskRequest `protobuf:"bytes,2,opt,name=task_request,json=taskRequest,proto3,oneof"`
}

type GatewayMessage_PeerRequest struct {
	// Peer invocation from another agent.
	PeerRequest *PeerRequest `protobuf:"bytes,3,opt,name=peer_request,json=peerRequest,proto3,oneof"`
}

type GatewayMessage_RosterUpdate struct {
	// Mesh membership change notification.
	RosterUpdate *RosterUpdate `protobuf:"bytes,4,opt,name=roster_update,json=rosterUpdate,proto3,oneof"`
}

type GatewayMessage_Error struct {
	// Protocol-level error.
	Error *Error `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

type GatewayMessage_DirectMessage struct {
	// Delivered direct message from another agent.
	DirectMessage *DirectMessage `protobuf:"bytes,6,opt,name=direct_message,json=directMessage,proto3,oneof"`
}

func (*GatewayMessage_Registered) isGatewayMessage_Msg() {}

func (*GatewayMessage_TaskRequest) isGatewayMessage_Msg() {}

func (*GatewayMessage_PeerRequest) isGatewayMessage_Msg() {}

func (*GatewayMessage_RosterUpdate) isGatewayMessage_Msg() {}

func (*GatewayMessage_Error) isGatewayMessage_Msg() {}

func (*GatewayMessage_DirectMessage) isGatewayMessage_Msg() {}

// RegisterRequest is sent by the agent as the first message on the stream.
type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human-readable agent name. Must be non-empty.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Agent role description.
	Role string `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	// Advertised capabilities for capability-based routing.
	Capabilities []string `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	// Bearer token for authentication. Must be non-empty.
	AuthToken string `protobuf:"bytes,4,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	// Extensible key-value metadata.
	Metadata      map[string]string `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_cortex_gateway_v1_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_gateway_v1_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_cortex_gateway_v1_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *RegisterRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RegisterRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *RegisterRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// RegisterResponse is sent by the gateway after successful registration.
type RegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Assigned agent UUID.
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Current number of agents in the mesh.
	PeerCount int32 `protobuf:"varint,2,opt,name=peer_count,json=peerCount,proto3" json:"peer_count,omitempty"`
	// Active run ID, if any. Empty string if no run is active.
	RunId         string `protobuf:"bytes,3,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_cortex_gateway_v1_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_gateway_v1_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_cortex_gateway_v1_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterResponse) GetPeerCount() int32 {
	if x != nil {
		return x.PeerCount
	}
	return 0
}

func (x *RegisterResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

// Heartbeat is sent periodically by the agent to maintain its health status.
type Heartbeat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agent ID assigned during registration.
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Current operational status.
	Status AgentStatus `protobuf:"varint,2,opt,name=status,proto3,enum=cortex.gateway.v1.AgentStatus" json:"status,omitempty"`
	// Number of tasks currently being processed.
	ActiveTasks int32 `protobuf:"varint,3,opt,name=active_tasks,json=activeTasks,proto3" json:"active_tasks,omitempty"`
	// Number of tasks queued locally.
	QueueDepth    int32 `protobuf:"varint,4,opt,name=queue_depth,json=queueDepth,proto3" json:"queue_depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_cortex_gateway_v1_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_gateway_v1_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_cortex_gateway_v1_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *Heartbeat) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Heartbeat) GetStatus() AgentStatus {
	if x != nil {
		return x.Status
	}
	return AgentStatus_AGENT_STATUS_UNSPECIFIED
}

func (x *Heartbeat) GetActiveTasks() int32 {
	if x != nil {
		return x.ActiveTasks
	}
	return 0
}

func (x *Heartbeat) GetQueueDepth() int32 {
	if x != nil {
		return x.QueueDepth
	}
	return 0
}

// TaskRequest is sent by the gateway to assign work to an agent.
type TaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique task identifier.
	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// Task prompt or instructions.
	Prompt string `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	// Tools available to the agent for this task.
	Tools []string `protobuf:"bytes,3,rep,name=tools,proto3" json:"tools,omitempty"`
	// Task timeout in milliseconds.
	TimeoutMs int64 `protobuf:"varint,4,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	// Contextual key-value pairs (run_id, team, upstream results, etc.).
	Context       map[string]string `protobuf:"bytes,5,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_cortex_gateway_v1_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_gateway_v1_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_cortex_gateway_v1_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *TaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *TaskRequest) GetTools() []string {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *TaskRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *TaskRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

// TaskResult is sent by the agent when a task completes or fails.
type TaskResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Task identifier matching the original TaskRequest.
	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// Outcome status.
	Status TaskStatus `protobuf:"varint,2,opt,name=status,proto3,enum=cortex.gateway.v1.TaskStatus" json:"status,omitempty"`
	// Result text or error message.
	ResultText string `protobuf:"bytes,3,opt,name=result_text,json=resultText,proto3" json:"result_text,omitempty"`
	// Time spent on the task in milliseconds.
	DurationMs int64 `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	// Number of input tokens consumed.
	InputTokens int32 `protobuf:"varint,5,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	// Number of output tokens produced.
	OutputTokens  int32 `protobuf:"varint,6,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_cortex_gateway_v1_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_gateway_v1_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_cortex_gateway_v1_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *TaskResult) GetResultText() string {
	if x != nil {
		return x.ResultText
	}
	return ""
}

func (x *TaskResult) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *TaskResult) GetInputTokens() int32 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *TaskResult) GetOutputTokens() int32 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

// StatusUpdate is sent by the agent to report progress.
type StatusUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agent ID assigned during registration.
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Current operational status.
	Status AgentStatus `protobuf:"varint,2,opt,name=status,proto3,enum=cortex.gateway.v1.AgentStatus" json:"status,omitempty"`
	// Human-readable progress description.
	Detail string `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	// Progress fraction from 0.0 to 1.0.
	Progress      float32 `protobuf:"fixed32,4,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusUpdate) Reset() {
	*x = StatusUpdate{}
	mi := &file_cortex_gateway_v1_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusUpdate) ProtoMessage() {}

func (x *StatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_gateway_v1_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusUpdate.ProtoReflect.Descriptor instead.
func (*StatusUpdate) Descriptor() ([]byte, []int) {
	return file_cortex_gateway_v1_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *StatusUpdate) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *StatusUpdate) GetStatus() AgentStatus {
	if x != nil {
		return x.Status
	}
	return AgentStatus_AGENT_STATUS_UNSPECIFIED
}

func (x *StatusUpdate) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *StatusUpdate) GetProgress() float32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

// PeerRequest is sent by the gateway to invoke this agent on behalf of another.
type PeerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique request identifier for correlating with PeerResponse.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Agent ID of the requesting agent.
	FromAgent string `protobuf:"bytes,2,opt,name=from_agent,json=fromAgent,proto3" json:"from_agent,omitempty"`
	// Capability being invoked.
	Capability string `protobuf:"bytes,3,opt,name=capability,proto3" json:"capability,omitempty"`
	// Prompt or instructions for the invocation.
	Prompt string `protobuf:"bytes,4,opt,name=prompt,proto3" json:"prompt,omitempty"`
	// Timeout in milliseconds.
	TimeoutMs     int64 `protobuf:"varint,5,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerRequest) Reset() {
	*x = PeerRequest{}
	mi := &file_cortex_gateway_v1_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerRequest) ProtoMessage() {}

func (x *PeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_gateway_v1_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerRequest.ProtoReflect.Descriptor instead.
func (*PeerRequest) Descriptor() ([]byte, []int) {
	return file_cortex_gateway_v1_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *PeerRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PeerRequest) GetFromAgent() string {
	if x != nil {
		return x.FromAgent
	}
	return ""
}

func (x *PeerRequest) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *PeerRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *PeerRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

// PeerResponse is sent by the agent in response to a PeerRequest.
type PeerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Request identifier matching the original PeerRequest.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Outcome status.
	Status TaskStatus `protobuf:"varint,2,opt,name=status,proto3,enum=cortex.gateway.v1.TaskStatus" json:"status,omitempty"`
	// Result text.
	Result string `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	// Time spent in milliseconds.
	DurationMs    int64 `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerResponse) Reset() {
	*x = PeerResponse{}
	mi := &file_cortex_gateway_v1_gateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerResponse) ProtoMessage() {}

func (x *PeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_gateway_v1_gateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerResponse.ProtoReflect.Descriptor instead.
func (*PeerResponse) Descriptor() ([]byte, []int) {
	return file_cortex_gateway_v1_gateway_proto_rawDescGZIP(), []int{9}
}

func (x *PeerResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PeerResponse) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *PeerResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *PeerResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

// RosterUpdate is sent by the gateway when mesh membership changes.
type RosterUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current list of all agents in the mesh.
	Agents        []*AgentInfo `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RosterUpdate) Reset() {
	*x = RosterUpdate{}
	mi := &file_cortex_gateway_v1_gateway_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RosterUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RosterUpdate) ProtoMessage() {}

func (x *RosterUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_gateway_v1_gateway_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RosterUpdate.ProtoReflect.Descriptor instead.
func (*RosterUpdate) Descriptor() ([]byte, []int) {
	return file_cortex_gateway_v1_gateway_proto_rawDescGZIP(), []int{10}
}

func (x *RosterUpdate) GetAgents() []*AgentInfo {
	if x != nil {
		return x.Agents
	}
	return nil
}

// AgentInfo describes a single agent in the mesh roster.
type AgentInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agent UUID.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Human-readable name.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Agent role description.
	Role string `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	// Advertised capabilities.
	Capabilities []string `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	// Current operational status.
	Status AgentStatus `protobuf:"varint,5,opt,name=status,proto3,enum=cortex.gateway.v1.AgentStatus" json:"status,omitempty"`
	// Extensible key-value metadata.
	Metadata      map[string]string `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_cortex_gateway_v1_gateway_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_gateway_v1_gateway_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_cortex_gateway_v1_gateway_proto_rawDescGZIP(), []int{11}
}

func (x *AgentInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AgentInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentInfo) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *AgentInfo) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *AgentInfo) GetStatus() AgentStatus {
	if x != nil {
		return x.Status
	}
	return AgentStatus_AGENT_STATUS_UNSPECIFIED
}

func (x *AgentInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// DirectMessage is used for agent-to-agent messaging.
// Appears in both AgentMessage (agent sends to gateway for routing)
// and GatewayMessage (gateway delivers to target agent).
type DirectMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique message identifier.
	MessageId string `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Target agent ID. Set by the sending agent; empty for broadcast delivery.
	ToAgent string `protobuf:"bytes,2,opt,name=to_agent,json=toAgent,proto3" json:"to_agent,omitempty"`
	// Sender agent ID. Set by the gateway on delivery.
	FromAgent string `protobuf:"bytes,3,opt,name=from_agent,json=fromAgent,proto3" json:"from_agent,omitempty"`
	// Message body.
	Content string `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	// Unix timestamp in milliseconds.
	Timestamp     int64 `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectMessage) Reset() {
	*x = DirectMessage{}
	mi := &file_cortex_gateway_v1_gateway_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectMessage) ProtoMessage() {}

func (x *DirectMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_gateway_v1_gateway_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectMessage.ProtoReflect.Descriptor instead.
func (*DirectMessage) Descriptor() ([]byte, []int) {
	return file_cortex_gateway_v1_gateway_proto_rawDescGZIP(), []int{12}
}

func (x *DirectMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *DirectMessage) GetToAgent() string {
	if x != nil {
		return x.ToAgent
	}
	return ""
}

func (x *DirectMessage) GetFromAgent() string {
	if x != nil {
		return x.FromAgent
	}
	return ""
}

func (x *DirectMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *DirectMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// BroadcastRequest sends a message to all connected agents.
// The gateway delivers it as DirectMessage to each agent except the sender.
type BroadcastRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Message body.
	Content       string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastRequest) Reset() {
	*x = BroadcastRequest{}
	mi := &file_cortex_gateway_v1_gateway_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastRequest) ProtoMessage() {}

func (x *BroadcastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_gateway_v1_gateway_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastRequest.ProtoReflect.Descriptor instead.
func (*BroadcastRequest) Descriptor() ([]byte, []int) {
	return file_cortex_gateway_v1_gateway_proto_rawDescGZIP(), []int{13}
}

func (x *BroadcastRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// Error represents a protocol-level error from the gateway.
// Fatal errors may be followed by stream closure.
type Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Machine-readable error code (e.g., "AUTH_FAILED", "INVALID_MESSAGE").
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// Human-readable error description.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_cortex_gateway_v1_gateway_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_gateway_v1_gateway_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_cortex_gateway_v1_gateway_proto_rawDescGZIP(), []int{14}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_cortex_gateway_v1_gateway_proto protoreflect.FileDescriptor

const file_cortex_gateway_v1_gateway_proto_rawDesc = "" +
	"\n" +
	"\x1fcortex/gateway/v1/gateway.proto\x12\x11cortex.gateway.v1\"\xf7\x03\n" +
	"\fAgentMessage\x12@\n" +
	"\bregister\x18\x01 \x01(\v2\".cortex.gateway.v1.RegisterRequestH\x00R\bregister\x12<\n" +
	"\theartbeat\x18\x02 \x01(\v2\x1c.cortex.gateway.v1.HeartbeatH\x00R\theartbeat\x12@\n" +
	"\vtask_result\x18\x03 \x01(\v2\x1d.cortex.gateway.v1.TaskResultH\x00R\n" +
	"taskResult\x12F\n" +
	"\rstatus_update\x18\x04 \x01(\v2\x1f.cortex.gateway.v1.StatusUpdateH\x00R\fstatusUpdate\x12F\n" +
	"\rpeer_response\x18\x05 \x01(\v2\x1f.cortex.gateway.v1.PeerResponseH\x00R\fpeerResponse\x12I\n" +
	"\x0edirect_message\x18\x06 \x01(\v2 .cortex.gateway.v1.DirectMessageH\x00R\rdirectMessage\x12C\n" +
	"\tbroadcast\x18\a \x01(\v2#.cortex.gateway.v1.BroadcastRequestH\x00R\tbroadcastB\x05\n" +
	"\x03msg\"\xad\x03\n" +
	"\x0eGatewayMessage\x12E\n" +
	"\n" +
	"registered\x18\x01 \x01(\v2#.cortex.gateway.v1.RegisterResponseH\x00R\n" +
	"registered\x12C\n" +
	"\ftask_request\x18\x02 \x01(\v2\x1e.cortex.gateway.v1.TaskRequestH\x00R\vtaskRequest\x12C\n" +
	"\fpeer_request\x18\x03 \x01(\v2\x1e.cortex.gateway.v1.PeerRequestH\x00R\vpeerRequest\x12F\n" +
	"\rroster_update\x18\x04 \x01(\v2\x1f.cortex.gateway.v1.RosterUpdateH\x00R\frosterUpdate\x120\n" +
	"\x05error\x18\x05 \x01(\v2\x18.cortex.gateway.v1.ErrorH\x00R\x05error\x12I\n" +
	"\x0edirect_message\x18\x06 \x01(\v2 .cortex.gateway.v1.DirectMessageH\x00R\rdirectMessageB\x05\n" +
	"\x03msg\"\x87\x02\n" +
	"\x0fRegisterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x04 \x01(\tR\tauthToken\x12L\n" +
	"\bmetadata\x18\x05 \x03(\v20.cortex.gateway.v1.RegisterRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"c\n" +
	"\x10RegisterResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"peer_count\x18\x02 \x01(\x05R\tpeerCount\x12\x15\n" +
	"\x06run_id\x18\x03 \x01(\tR\x05runId\"\xa2\x01\n" +
	"\tHeartbeat\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x126\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1e.cortex.gateway.v1.AgentStatusR\x06status\x12!\n" +
	"\factive_tasks\x18\x03 \x01(\x05R\vactiveTasks\x12\x1f\n" +
	"\vqueue_depth\x18\x04 \x01(\x05R\n" +
	"queueDepth\"\xf6\x01\n" +
	"\vTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x12\x14\n" +
	"\x05tools\x18\x03 \x03(\tR\x05tools\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x04 \x01(\x03R\ttimeoutMs\x12E\n" +
	"\acontext\x18\x05 \x03(\v2+.cortex.gateway.v1.TaskRequest.ContextEntryR\acontext\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe6\x01\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x125\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1d.cortex.gateway.v1.TaskStatusR\x06status\x12\x1f\n" +
	"\vresult_text\x18\x03 \x01(\tR\n" +
	"resultText\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x03R\n" +
	"durationMs\x12!\n" +
	"\finput_tokens\x18\x05 \x01(\x05R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x06 \x01(\x05R\foutputTokens\"\x95\x01\n" +
	"\fStatusUpdate\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x126\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1e.cortex.gateway.v1.AgentStatusR\x06status\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\x12\x1a\n" +
	"\bprogress\x18\x04 \x01(\x02R\bprogress\"\xa2\x01\n" +
	"\vPeerRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"from_agent\x18\x02 \x01(\tR\tfromAgent\x12\x1e\n" +
	"\n" +
	"capability\x18\x03 \x01(\tR\n" +
	"capability\x12\x16\n" +
	"\x06prompt\x18\x04 \x01(\tR\x06prompt\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x05 \x01(\x03R\ttimeoutMs\"\x9d\x01\n" +
	"\fPeerResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x125\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1d.cortex.gateway.v1.TaskStatusR\x06status\x12\x16\n" +
	"\x06result\x18\x03 \x01(\tR\x06result\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x03R\n" +
	"durationMs\"D\n" +
	"\fRosterUpdate\x124\n" +
	"\x06agents\x18\x01 \x03(\v2\x1c.cortex.gateway.v1.AgentInfoR\x06agents\"\xa4\x02\n" +
	"\tAgentInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\x126\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1e.cortex.gateway.v1.AgentStatusR\x06status\x12F\n" +
	"\bmetadata\x18\x06 \x03(\v2*.cortex.gateway.v1.AgentInfo.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa0\x01\n" +
	"\rDirectMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x19\n" +
	"\bto_agent\x18\x02 \x01(\tR\atoAgent\x12\x1d\n" +
	"\n" +
	"from_agent\x18\x03 \x01(\tR\tfromAgent\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\",\n" +
	"\x10BroadcastRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\x96\x01\n" +
	"\vAgentStatus\x12\x1c\n" +
	"\x18AGENT_STATUS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11AGENT_STATUS_IDLE\x10\x01\x12\x18\n" +
	"\x14AGENT_STATUS_WORKING\x10\x02\x12\x19\n" +
	"\x15AGENT_STATUS_DRAINING\x10\x03\x12\x1d\n" +
	"\x19AGENT_STATUS_DISCONNECTED\x10\x04*w\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15TASK_STATUS_COMPLETED\x10\x01\x12\x16\n" +
	"\x12TASK_STATUS_FAILED\x10\x02\x12\x19\n" +
	"\x15TASK_STATUS_CANCELLED\x10\x032a\n" +
	"\fAgentGateway\x12Q\n" +
	"\aConnect\x12\x1f.cortex.gateway.v1.AgentMessage\x1a!.cortex.gateway.v1.GatewayMessage(\x010\x01B4Z2github.com/cortex/sidecar/internal/proto/gatewayv1b\x06proto3"

var (
	file_cortex_gateway_v1_gateway_proto_rawDescOnce sync.Once
	file_cortex_gateway_v1_gateway_proto_rawDescData []byte
)

func file_cortex_gateway_v1_gateway_proto_rawDescGZIP() []byte {
	file_cortex_gateway_v1_gateway_proto_rawDescOnce.Do(func() {
		file_cortex_gateway_v1_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cortex_gateway_v1_gateway_proto_rawDesc), len(file_cortex_gateway_v1_gateway_proto_rawDesc)))
	})
	return file_cortex_gateway_v1_gateway_proto_rawDescData
}

var file_cortex_gateway_v1_gateway_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_cortex_gateway_v1_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_cortex_gateway_v1_gateway_proto_goTypes = []any{
	(AgentStatus)(0),         // 0: cortex.gateway.v1.AgentStatus
	(TaskStatus)(0),          // 1: cortex.gateway.v1.TaskStatus
	(*AgentMessage)(nil),     // 2: cortex.gateway.v1.AgentMessage
	(*GatewayMessage)(nil),   // 3: cortex.gateway.v1.GatewayMessage
	(*RegisterRequest)(nil),  // 4: cortex.gateway.v1.RegisterRequest
	(*RegisterResponse)(nil), // 5: cortex.gateway.v1.RegisterResponse
	(*Heartbeat)(nil),        // 6: cortex.gateway.v1.Heartbeat
	(*TaskRequest)(nil),      // 7: cortex.gateway.v1.TaskRequest
	(*TaskResult)(nil),       // 8: cortex.gateway.v1.TaskResult
	(*StatusUpdate)(nil),     // 9: cortex.gateway.v1.StatusUpdate
	(*PeerRequest)(nil),      // 10: cortex.gateway.v1.PeerRequest
	(*PeerResponse)(nil),     // 11: cortex.gateway.v1.PeerResponse
	(*RosterUpdate)(nil),     // 12: cortex.gateway.v1.RosterUpdate
	(*AgentInfo)(nil),        // 13: cortex.gateway.v1.AgentInfo
	(*DirectMessage)(nil),    // 14: cortex.gateway.v1.DirectMessage
	(*BroadcastRequest)(nil), // 15: cortex.gateway.v1.BroadcastRequest
	(*Error)(nil),            // 16: cortex.gateway.v1.Error
	nil,                      // 17: cortex.gateway.v1.RegisterRequest.MetadataEntry
	nil,                      // 18: cortex.gateway.v1.TaskRequest.ContextEntry
	nil,                      // 19: cortex.gateway.v1.AgentInfo.MetadataEntry
}
var file_cortex_gateway_v1_gateway_proto_depIdxs = []int32{
	4,  // 0: cortex.gateway.v1.AgentMessage.register:type_name -> cortex.gateway.v1.RegisterRequest
	6,  // 1: cortex.gateway.v1.AgentMessage.heartbeat:type_name -> cortex.gateway.v1.Heartbeat
	8,  // 2: cortex.gateway.v1.AgentMessage.task_result:type_name -> cortex.gateway.v1.TaskResult
	9,  // 3: cortex.gateway.v1.AgentMessage.status_update:type_name -> cortex.gateway.v1.StatusUpdate
	11, // 4: cortex.gateway.v1.AgentMessage.peer_response:type_name -> cortex.gateway.v1.PeerResponse
	14, // 5: cortex.gateway.v1.AgentMessage.direct_message:type_name -> cortex.gateway.v1.DirectMessage
	15, // 6: cortex.gateway.v1.AgentMessage.broadcast:type_name -> cortex.gateway.v1.BroadcastRequest
	5,  // 7: cortex.gateway.v1.GatewayMessage.registered:type_name -> cortex.gateway.v1.RegisterResponse
	7,  // 8: cortex.gateway.v1.GatewayMessage.task_request:type_name -> cortex.gateway.v1.TaskRequest
	10, // 9: cortex.gateway.v1.GatewayMessage.peer_request:type_name -> cortex.gateway.v1.PeerRequest
	12, // 10: cortex.gateway.v1.GatewayMessage.roster_update:type_name -> cortex.gateway.v1.RosterUpdate
	16, // 11: cortex.gateway.v1.GatewayMessage.error:type_name -> cortex.gateway.v1.Error
	14, // 12: cortex.gateway.v1.GatewayMessage.direct_message:type_name -> cortex.gateway.v1.DirectMessage
	17, // 13: cortex.gateway.v1.RegisterRequest.metadata:type_name -> cortex.gateway.v1.RegisterRequest.MetadataEntry
	0,  // 14: cortex.gateway.v1.Heartbeat.status:type_name -> cortex.gateway.v1.AgentStatus
	18, // 15: cortex.gateway.v1.TaskRequest.context:type_name -> cortex.gateway.v1.TaskRequest.ContextEntry
	1,  // 16: cortex.gateway.v1.TaskResult.status:type_name -> cortex.gateway.v1.TaskStatus
	0,  // 17: cortex.gateway.v1.StatusUpdate.status:type_name -> cortex.gateway.v1.AgentStatus
	1,  // 18: cortex.gateway.v1.PeerResponse.status:type_name -> cortex.gateway.v1.TaskStatus
	13, // 19: cortex.gateway.v1.RosterUpdate.agents:type_name -> cortex.gateway.v1.AgentInfo
	0,  // 20: cortex.gateway.v1.AgentInfo.status:type_name -> cortex.gateway.v1.AgentStatus
	19, // 21: cortex.gateway.v1.AgentInfo.metadata:type_name -> cortex.gateway.v1.AgentInfo.MetadataEntry
	2,  // 22: cortex.gateway.v1.AgentGateway.Connect:input_type -> cortex.gateway.v1.AgentMessage
	3,  // 23: cortex.gateway.v1.AgentGateway.Connect:output_type -> cortex.gateway.v1.GatewayMessage
	23, // [23:24] is the sub-list for method output_type
	22, // [22:23] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_cortex_gateway_v1_gateway_proto_init() }
func file_cortex_gateway_v1_gateway_proto_init() {
	if File_cortex_gateway_v1_gateway_proto != nil {
		return
	}
	file_cortex_gateway_v1_gateway_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Register)(nil),
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_TaskResult)(nil),
		(*AgentMessage_StatusUpdate)(nil),
		(*AgentMessage_PeerResponse)(nil),
		(*AgentMessage_DirectMessage)(nil),
		(*AgentMessage_Broadcast)(nil),
	}
	file_cortex_gateway_v1_gateway_proto_msgTypes[1].OneofWrappers = []any{
		(*GatewayMessage_Registered)(nil),
		(*GatewayMessage_TaskRequest)(nil),
		(*GatewayMessage_PeerRequest)(nil),
		(*GatewayMessage_RosterUpdate)(nil),
		(*GatewayMessage_Error)(nil),
		(*GatewayMessage_DirectMessage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cortex_gateway_v1_gateway_proto_rawDesc), len(file_cortex_gateway_v1_gateway_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cortex_gateway_v1_gateway_proto_goTypes,
		DependencyIndexes: file_cortex_gateway_v1_gateway_proto_depIdxs,
		EnumInfos:         file_cortex_gateway_v1_gateway_proto_enumTypes,
		MessageInfos:      file_cortex_gateway_v1_gateway_proto_msgTypes,
	}.Build()
	File_cortex_gateway_v1_gateway_proto = out.File
	file_cortex_gateway_v1_gateway_proto_goTypes = nil
	file_cortex_gateway_v1_gateway_proto_depIdxs = nil
}
